# Build settings
# remote_theme: cotes2020/jekyll-theme-chirpy
# plugins:
# - jekyll-remote-theme
theme: minima
  skin: dark
  social_links:
    - title: at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/animulay2020"

