remote_theme: piharpi/jekyll-klise

title: Aniruddha Mulay
description: >-
  Tech journal - notes on Distributed Systems, Systems Programming, Databases, GPU ...
lang: en-US
timezone: America/Los_Angeles
mode: dark

author:
  name: Aniruddha Mulay
  bio: >-
    Software Engineer interested in Distributed Systems, Scalability, Observability (o11y).
  username: animulay
  github: animulay
  twitter: https://x.com/animulay2020
  facebook:
  email:
  avatar:

url: "https://animulay.github.io"
baseurl: "https://github.com/animulay"
permalink: /:title/
google_analytics:
fb_appid:

collections:
  posts:
    output: true

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

number_of_posts: 10

sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
