
# Build settings
remote_theme: cotes2020/jekyll-theme-chirpy

lang: en
timezone: America/Los_Angeles

social:
  links:
    https://x.com/animulay2020

theme_mode: dark

avatar: "/commons/avatar.jpg"

paginate: 10
